name: cdk-deploy-prod

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy-prod:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: CDK Deploy to PROD
        uses: ./.github/actions/cdk-deploy
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_PROD }}
          aws-region: ${{ secrets.AWS_REGION_PROD }}
          env: prod
